CREATE TABLE [dbo].[User]
(
  [Id]  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [Name] NVARCHAR(100) NOT NULL,
  [Email] NVARCHAR(100) NOT NULL UNIQUE,
  [PasswordHash] NVARCHAR(255) NOT NULL,
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
  [UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
  [IsActive] BIT NOT NULL DEFAULT 1,
  [LastLogin] DATETIME NULL,
  [Role] NVARCHAR(50) NOT NULL DEFAULT 'User',
  
)
